from sqlalchemy import BigInteger, Identity, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class User(Base):
    """Учётная запись пользователя приложения.

    Attributes:
        user_id: Уникальный идентификатор, генерируемый последовательностью
            ``GENERATED BY DEFAULT AS IDENTITY`` на стороне PostgreSQL.
        username: Отображаемое имя пользователя.
        password_hash: Хэш пароля, рассчитанный на стороне приложения.
    """

    __tablename__ = "users"

    user_id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(),
        primary_key=True,
    )
    username: Mapped[str] = mapped_column(String, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
